config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
    get '/register', to:'users#new'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/pin', to: 'sessions#pin'
    post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end

  end

  #nested routes allow we to capture the relationship. In this case, It is supposed that
  # In each post, I have multiple comments.
  #In addition, the path will be nested in a way such as posts/:post_id/comments which is exactly I want for.
  #Shallow Nesting: One way to avoid deep nesting under and to build minimal amount of information.

  resources :categories, only: [:create, :new, :show]
  resources :users, only: [:show, :create, :edit, :update]

end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable
  include Sluggable

  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories

  validates :title, presence: true
  validates :description, presence: true

  sluggable_column :title




  #Validation is always added in the model layer
  #Validation won't be trigger until you make an 'action'
  #check the error for the validation false : post.errors.full_message
  #                                          object.errors
  #since the error is already only the object itself, then
end


app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:show, :index]
  before_action :require_creator, only: [:edit, :update]

  def index
    @posts = Post.all.sort_by{ |x| x.total_votes}.reverse
    #render index.html.erb
  end

  def show
    @comment = Comment.new
    #@post = Post.find(params[:id])
    #for specific and each post
    #render the show template
  end

  def new
   @post = Post.new
  end

  def create
   @post = Post.new(post_params)
   @post.creator = current_user  #check again: identify user or creator

   if @post.save
     flash[:notice] = "Your post is created."
     redirect_to posts_path
   else  #validation error #render means we have the access to the instance variable
     render 'new'
   end
  end

  def edit
  end

  def update
  if @post.update(post_params)
     flash[:notice] = "Your post is updated."
     redirect_to posts_path
   else  #validation error
     render 'edit'
   end
  end

  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])

    respond_to do |format|
      format.html do
        if @vote.valid?
          flash[:notice] = 'Your vote is counted.'
        else
          flash[:error] = 'You can only vote once.'
        end
        redirect_to :back
      end
      format.js
      # expecting a file called vote.js.erb
    end
  end

  private
  def post_params
   params.require(:post).permit(:title, :description, category_ids: [])
  end

  def set_post
    @post = Post.find_by slugs: params[:id]
  end

  def require_creator
    access_denied unless logged_in? and (current_user == @post.creator || current_user.admin?)
  end


end

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>



<%= form_for @post do |f| %>
  <div class="control-group well">
  <%= f.label :title %>
  <%= f.text_field :title %>
  </div>
  <div class="control-group well">
  <%= f.label :description %>
  <%= f.text_area :description, row: 3, class: "span4" %>
  </div>
  <div class='control-group'>
    <%= f.label "Categories" %>
    <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
      <% cb.label(class: "checkbox inline") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
  </div>

  <%= f.submit "Create Post", class: 'btn btn-primary' %>
<% end %>




app/views/posts/_post.html.erb


<div class="row">
  <div class='span0 well text-center'>
    <%= link_to vote_post_path(post, vote: true), method: 'post', remote: true do %>
      <i class='icon-arrow-up'></i>
    <% end %>
    <br/>
    <span id='post_<%= post.slugs %>_votes'><%= post.total_votes %> votes</span>
    <br/>
    <%= link_to vote_post_path(post, vote: false), method: 'post', remote: true do %>
      <i class='icon-arrow-down'></i>
    <% end %>
  </div>

  <div class="span8 well">
    <%= render post.categories %>
    <br/>
    <p><strong><%= post.title %></strong></p>
    <p><%= post.description %></p>
    <p>
      <span class="quiet">posted by</span> <%= link_to post.creator.username, user_path(post.creator) %>
      <small>at <%= display_datetime(post.created_at) %></small>
    <p>
       <small>
        <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
        </span>
       </small>
    </p>
    </p>
  </div>
</div>







app/views/posts/edit.html.erb
<h4>Edit a post</h4>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: "All Posts" %>

<% @posts.each do |post| %>
  <%= render "post", post: post %>
<% end %>

app/views/posts/new.html.erb


<h4>Create a post</h4>

<%= render 'form' %>

app/views/posts/show.html.erb
<% if logged_in? %>
  <p class='pull-right'>
    [<%= link_to 'edit this post', edit_post_path(@post)%>]
  </p>
<% end %>

<p>
<%= render @post.categories %>
</p>


<%= render 'shared/content_title', title: @post.title %>
<p>
  <%= @post.description %>
  <hr>
</p>

<% if logged_in? %>
 <%= form_for [@post, @comment] do |f| %>
  <%= render 'shared/errors', obj: @comment %>
  <div class='control-group'>
    <%= f.label :body, 'Comment' %>
    <%= f.text_area :body, rows: 3, class: 'span4' %>
  </div>
  <%= f.submit "Create Comment", class: "btn btn-primary" %>
 <% end %>
<% end %>

<h5>All the comments:</h5>

<% @post.reload.comments.each do |comment| %>
<div class='row'>
  <div class='span0 well text-center'>
  <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
    <i class='icon-arrow-up'></i>
  <% end %>
  <br/>
  <span id="comment_<%= comment.id %>_votes"><%= comment.total_votes %> votes</span>
  <br/>
    <%= link_to vote_post_comment_path(comment.post, comment, vote:true), method: 'post', remote: true do %>
    <i class='icon-arrow-down'></i>
  <% end %>
  </div>
  <div class="well span8">
    <en>"<%= comment.body %>"</en>
    <br/>
    <span class="quiet">by</span> <%= comment.creator.username %>
    <small>at <%= display_datetime(comment.created_at) %></small>
  </div>
</div>
<% end%>



app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $("#post_<%= @post.slugs%>_votes").html("<%= @post.total_votes%> votes")
<% else %>
  alert("You can only vote once.");
<% end %>
// inside this file, you can also have the access to instance variable