config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'
    get '/register', to:'users#new'
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    get '/logout', to: 'sessions#destroy'
    get '/pin', to: 'sessions#pin'
    post '/pin', to: 'sessions#pin'

  resources :posts, except: [:destroy] do
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end

  end

  #nested routes allow we to capture the relationship. In this case, It is supposed that
  # In each post, I have multiple comments.
  #In addition, the path will be nested in a way such as posts/:post_id/comments which is exactly I want for.
  #Shallow Nesting: One way to avoid deep nesting under and to build minimal amount of information.

  resources :categories, only: [:create, :new, :show]
  resources :users, only: [:show, :create, :edit, :update]

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, :class => 'brand' %>
  </li>
</ul>
<ul class='btn-group nav_item'>
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
     Categories <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
      <% Category.all.each do |category| %>
      <li><%= link_to category.name, category_path(category) %></li>
      <% end %>
      <% if logged_in? and current_user.admin? %>
        <li class='divider'></li>
        <li>
          <%= link_to(new_category_path) do %>
          <i class="icon-plus"></i>
          New Category
          <% end %>
        </li>
      <% end %>
    </ul>
</ul>

<% if logged_in? %>
<ul class="nav">
  <li>
    <%= link_to 'New Post', new_post_path %>
  </li>
</ul>

<ul class='btn-group nav_item'>
  <ul>
    <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
      <%= current_user.username %>
      <span class='caret'></span>
    <% end %>
    <ul class='dropdown-menu'>
      <li>
        <%= link_to edit_user_path(current_user) do %>
          <i class='icon-pencil'></i>
          Edit Profile
        <% end %>
      </li>
      <li>
        <%= link_to user_path(current_user) do %>
          <i class='icon-user'></i>
           View Profile
        <% end %>
      </li>
      <li>
        <%= link_to logout_path do %>
          <i class='icon-circle-arrow-left'></i>
           Logout
        <% end %>
      </li>
    </ul>
  </ul>
</ul>
<ul class="nav">
  <li>
    <%= link_to 'Log out', logout_path %>
  </li>
</ul>
<% else #logged out condition %>
<ul class="nav">
  <li>
    <%= link_to 'Register', register_path %>
  </li>
</ul>
<ul class="nav">
  <li>
    <%= link_to 'Log in', login_path%>
  </li>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>